name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js e cache do npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3️⃣ Instalar dependências
      - name: Instalar dependências
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # 4️⃣ Instalar Playwright e dependências do sistema
      - name: Instalar Playwright (Chromium + deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libatk1.0-0 \
            libgtk-3-0 \
            libdrm2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libasound2-plugins \
            fonts-liberation \
            libpangocairo-1.0-0
          npx playwright install --with-deps chromium

      # 5️⃣ Build da extensão
      - name: Build extensão
        run: npm run build

      # 6️⃣ Testes E2E com Chromium headful + extensão
      - name: Teste E2E
        run: xvfb-run -a -s "-screen 0 1920x1080x24" npx playwright test --config=my-chrome-extension/playwright.config.ts

      # 7️⃣ Publicar relatório HTML do Playwright
      - name: Publicar relatório HTML do Teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: my-chrome-extension/playwright-report

      # 8️⃣ Publicar pacote da extensão (ZIP)
      - name: Publicar o pacote da extensão (ZIP)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: my-chrome-extension/dist/extension.zip
